[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[mounts]]
mountPath = "/app/.data"
